###
GET http://localhost:8080/categories

###
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Electronics"
}

###
GET http://localhost:8080/categories/1

###
PUT http://localhost:8080/categories/1
Content-Type: application/json

{
  "name": "Updated Electronics"
}

###
DELETE http://localhost:8080/categories/1
